services:
  frontend:
    image: rpg/frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
      - ./index.html:/app/index.html
      - ./public:/app/public
      - ./package.json:/app/package.json

  backend:
    image: rpg/backend:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 5001:5000